---
title: Lecture script
author: <a href = "https://lovetoken.github.io">lovetoken</a>
date: "`r Sys.Date()`"
output: 
  html_document:
    fig_height: 6
    toc: yes
    toc_depth: 3
    toc_float: yes
    keep_md: yes
---

<style type="text/css">@import url("https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/yeti/bootstrap.min.css")</style><br>

```{r env, echo=FALSE, warning=FALSE, message=FALSE}
## attach library
pacman::p_load("useful.lovetoken", "knitr", "dplyr", "ggplot2", "data.table")
opts_chunk$set(fig.path = "output/figure/", fig.align = "center", out.width = "80%", 
               warning = F, message = F)
```

도로교통공단 빅데이터 전문가 양성 실습교육  
2일차 : 조금 더 세련된 데이터 분석을 도와줄 R 프로그래밍<br><br><br>  

## 첫인사

많이 피곤하시죠!?  
저도 피곤함과 멀어지기 위해 부단히 노력하고 애를 쓰다 보니 많이 피곤하네요..  
혹시 여러분께선 업무에 있어서 피곤함을 느끼시는 이유 중 하나를 생각해 보실 수 있으신가요??  
저는 직장인 개개인의 상황을 정확하게 알지 못하지만, 어떠한 직무이건 간에 엑셀프로그램을 켜 데이터를 살펴보고, 취합하고, 분석하는 어찌 보면 끔찍한 쳇바퀴 도는 행위들이 여러분의 업무부담을 가중시킬것이라 추측하고 있답니다.  
그리고 제가 우려하는 건 이러한 일이 더욱더 심해질 것 같다는 건데요.  

직감에 의한 의사결정과 근거기반에 의한 의사결정이 계속 상호보완적으로 되었던 복잡한 세상에서,  
점점 데이터를 수집∙저장∙배포 할 수 있는 기술들이 발전하는 현시대에, 분석 및 근거 기반에 의한 의사결정은 더욱 중요해지고 인간의 본성에 의해 많이 채택돼 점점 중요한 트렌드로 가고 있다 생각합니다.
이런 상황에서 우리가 어떠한 직무를 하고 있건 간 상관없이 쳇바퀴 도는 피곤함과 멀어질 수 있을지 고민해 볼 수 있는 시간이 되었으면 하는 바람으로,  
부담은 많이 되지만 강단에 오른 송효진이라고 합니다.<br><br><br>  

## 강의주제

오늘은 앞서 말한 쳇바퀴 도는 요소를 최대한 줄이고 조금 더 세련된 데이터 분석을 도와줄 R 프로그래밍이란 주제로 강의를 진행해 보고자 합니다.  
우리가 R 프로그래밍을 알아보기 이전에 먼저 하고 싶은 이야기가 있습니다.  
그것은 바로 현재의 데이터 분석 패러다임인데요.  
저는 현재 데이터 분석 패러다임을 "3C" 로 표현하고 싶습니다.  

Connectivity, Cloud service, Computer science

"Connectivity" 란 접근성, 특히 정보에 대한 접근성이 높아졌다는 것을 주목해 볼 필요가 있습니다.  
인터넷과 웹의 발전으로 정보를 누구나 습득하기 쉬워졌지요.  
이는 일반적인 정리된 글이나, 기사, 의견, 댓글, 그림, 영상, 보고서, 논문 등뿐만 아니라 분석의 대상이 되는 데이터도 마찬가지 이야기가 되었죠.  

"Cloud service" 는 정보와 기술의 배포를 급격히 가속화 시킨 혁신적인 서비스로 볼 수 있습니다.  
최근에 이어 지금까지도 실생활에 다양한 방법들로 녹아들고 있지요.  
가장 체감하기 쉬운 대표적인 예로 Cloud storage service 가 있을 텐데,  
쉽게 말해 인터넷에서 사용할 수 있는 하드디스크 드라이브로 볼 수 있겠죠.  
이를 통해 언제 어디서든 자신의 파일들을 관리할 수 있는 자유가 생겼고, 많은 제약이 사라지게 되었습니다.  
앞서 말한 데이터의 Connectivity 도 Cloud service 를 통해 접근성을 더욱 높일 수 있게 되었다고 볼 수 있겠죠.  

"Computer science" 는 Connectivity 와 Cloud service 를 가능하게 해준 장본인이라 비유하고 싶은데요.  
컴퓨터를 통해 아날로그에서 디지털로 데이터를 관리할 수 있게 되었고, 이로써 다양하고 거대한 혁신들이 생깁니다.  
지금은 컴퓨터란 물건 없이 데이터를 분석하는 것을 상상할 수 있나요?  
그렇지 못할 겁니다.  
연산능력이 인간보다 월등한 컴퓨터의 특수성을 이용해, 인간은 많은 도전들을 할 수 있게 되었고 여러분만의 독자적인 분석아이디어를 구현해보며 연구할 수 있게 되었죠.<br><br><br>  

## 데이터 분석에 프로그래밍을 접목하려는 목적

이렇게 소개해 드린 "3C" 는 어찌 보면 이미 알고 계신 고리타분한 이야기일지도 모르겠습니다만, 데이터 분석의 패러다임을 뒤바꿔 놓고 있습니다.  
Cloud service 를 통해 물리적인 Computing power 를 사용하지 않고도 원격에서 거대한 리소스를 공공재처럼 사용하여 분석하는 게 가능해졌고,  
대상이 무엇이 되었던 Connectivity 가 쉬워 지면서 자석과 자석이 서로 끌리듯 연결 및 융합되려 하고 있으며, 이 과정 중에 다양한 형태의 데이터가 Computer science 에 의해 수집되고 저장 ∙ 배포될 것입니다.  
이러한 환경에서 기존의 쳇바퀴를 도는 데이터 분석 패러다임은 이젠 탈피할 필요성이 있을 것입니다.   

빠르게 탈피하기 위해선 "3C" 중에 언급된 컴퓨터와 친해져 보는 것이 가장 빠른 방법인 거 같아요.  
원래 컴퓨터와 친하게 지내고 있을진 몰라도, 컴퓨터를 조금 더 이해해서 컴퓨터적 사고능력을 가진 수준의 친숙함을 가진다면 자연스럽고 빠르게 기존의 패러다임에서 탈피할 수 있게 될 거라 단언합니다.  
컴퓨터에 종속되는 게 아닌 이용을 하기 위해선 프로그래밍을 알아야 하고, 배운 걸 실제로 써먹어 자신의 삶의 질을 높이는 것을 목표로 설정해 볼 법한 미션이죠.  

본 강의주제인 R을 소개하기도 전에 이렇게 장황한 이야기를 한 것은 목적설정 없인 R은 그저 한낱 길가에 버려진 도구로 볼 수밖에 없기 때문입니다.  
그렇습니다. 패러다임을 적극적으로 이용하고 자신의 아이디어를 주체적으로 표현하고자 하며, 세련된 것을 추구하는 인간의 본성에 대한 욕구를 충족하고자 한다면 꼭 업무가 아니더라도 개인적으로라도 프로그래밍을 배워 볼 만하다 라는 이야기를 드리며, 강력히 추천하는바 입니다.
그런 의미로 이 슬라이드를 준비했죠.

자 여기 4개의 정체불명의 데이터가 존재합니다.  
정말 적은 개수의 데이터죠?  
이 상태를 서비스 초기 단계로 비유해 보고 싶군요, 서비스 초기 단계엔 이처럼 많은 데이터를 가지지 못하고 Small 한 데이터가 있을 거예요.  
하지만 데이터의 양이 Small 이던 Big 이던 상관없이 분석기반을 프로그래밍을 통해 만들어 놓을 순 있죠.  
예를 들어 본 데이터들을 설명하는 모델링이 목적이라 하면 이정도의 적은 코딩을 통해 분석기반을 만들어 놓을 것입니다.  
자 그리고 이 코드를 서버에 심어놓고 새로운 데이터의 갱신과 결과 리포팅을 컴퓨터에게 맡겨놓기만 하면  
단순반복적인 굴레에서 벗어나 즉각적으로 서비스 자체의 흐름을 파악하는 데 집중할 수 있고, 서비스가 실제 어떤 이슈를 낼 수 있는지, 데이터 분석방법은 어떻게 해야 좋을지, 서비스의 질은 어떻게 높일 것인지,  
좀 더 이성적이고 본질적인 인성적인 고민을 할 수 있는 기회로 다가오게 될 것입니다.  

어떠한가요? 준비한 예제가 별 볼 일 없는 예제이지만 R이란 프로그래밍의 도구가 여러분께 제공할 효용이 생각보다 클 것이다 란걸 느끼셨다면 좋겠습니다만..  
흠 어찌 되었건 지금 보여드린 것은 여러분이 원하는 연구의 결과물이 아니잖아요?  
여러분 각자 지금 맞닥뜨리고 있는 다양한 과제나 연구를 이렇게 실현하는 것은 어찌 보면 남이 해줄 수 없고 나 자신 혹은 자신의 팀∙집단만이 할 수 있는 일이라 생각해요.  
자신의 힘으로 직접 프로그래밍해보며 Realize하고 구현시키는 것이 매우 중요합니다.  
그럼으로써 소소한 성취감을 통해 자신감을 얻으신다면 빠르게 실력을 쌓아 경쟁력을 갖출 수 있게 될 거라 확신합니다.<br><br><br>  

## 기초 데이터 분석 및 실습

그런 의미로 실습시간을 가져볼까요?  
직접 해보는 것만큼 중요한 것은 없을 겁니다.  
진행했던 도로교통공단에서의 프로젝트에 사용했던 데이터를 이용하여 R 실습을 같이해 보도록 하죠.  

*실습 진행*<br><br><br>  

## 오픈소스의 지향점

자 지금까지 실습해 본 R에 대해서 추가로 설명해 드리고 싶은 게 있답니다.  
알고 있으신 분들은 아시겠지만, R의 큰 특징은 오픈소스 프로그래밍 언어라는 것입니다.  
오픈소스를 주제로 설명하고 싶은 게 있습니다.  
그림을 하나 준비해 보았는데요, 어떤 그림인 것 같나요?  
